### ISSUE TITLE
errors when compiling with air

### ISSUE THREAD

**Issue by Adlerkampf** [f-taxes/f-taxes#1]
When I try to build the project with air on Windows, I'm getting this error message 
`go: open C:\Users\user\Desktop\vscode\f-taxes\goftx\go.mod: The system cannot find the path specified.
failed to build, error: exit status 1`

It indicates that there need's to be a nother GitHub repository called goftx(https://github.com/grishinsana/goftx). So I also cloned that repository.

Then I tried to run the air command again, and I am not getting the error message above anymore but instead this error message

```
# github.com/f-taxes/f-taxes/backend/ftx
backend\ftx\ftxSource.go:28:77: undefined: goftx.WithSubaccount
backend\ftx\ftxSource.go:75:34: s.client.Fills.Fills undefined (type goftx.Fills has no field or method Fills)
backend\ftx\ftxSource.go:75:48: undefined: models.FillsParams
failed to build, error: exit status 2
```

**Comment by trading-peter** [comment]
Ay, thanks for making me aware. I forgot to mention that part in the docs.
Please clone https://github.com/trading-peter/goftx instead of grishinsana/goftx and put it next to the f-taxes project folder.
This will be fixed once the ftx integration is moved into a plugin.

**Comment by trading-peter** [comment]
I tried to build/run on windows and found another issue with air. I've updated the readme with the fix.
Please pull the main branch again and follow the instructions.
Let me know how it goes.

**Comment by Adlerkampf** [comment]
Thanks a lot for your support, it worked!
